#!/bin/sh
set -e
for d in $(find $HOME/dev/git -type d -name mirrors -prune -o -type d -name .git -print | sort); do
	u=$(echo $d | cut -d/ -f6)
	r=$(echo $d | cut -d/ -f7)
	echo "updating $u/$r..."
	git -C $d remote remove origin
	if [ $r = 'acid.vegas' ]; then
		git -C $d remote add origin git@github.com:$u/acidvegas.github.io.git
		git -C $d remote set-url --add --push origin git@github.com:$u/acidvegas.github.io.git
		git -C $d remote set-url --add --push origin git@gitlab.com:$u/acidvegas.gitlab.io.git
		git -C $d remote set-url --add --push origin git@contra:$r.git
	elif [ $r = 'supernets.org' ]; then
		git -C $d remote add origin git@github.com:$u/supernets.github.io.git
		git -C $d remote set-url --add --push origin git@github.com:$u/supernets.github.io.git
		git -C $d remote set-url --add --push origin git@gitlab.com:$u/supernets.gitlab.io.git
		git -C $d remote set-url --add --push origin git@contra:$r.git
	else
		git -C $d remote add origin git@github.com:$u/$r.git
		git -C $d remote set-url --add --push origin git@github.com:$u/$r.git
		git -C $d remote set-url --add --push origin git@gitlab.com:$u/$r.git
		git -C $d remote set-url --add --push origin git@contra:$r.git
	fi
	git -C $d config user.signingkey 441EB0F297E0DCF0AEF2F711EF4B922DB85DC9DE
done